///////////////////////////////////////////////////////////
//
//  EnterpriseArchitextClass1.cpp
//  Implementation of the Class Class1
//  Generated by Enterprise Architect
//  Created on:      25-May-2003 02:48:46
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////

#include "EnterpriseArchitextClass1.h"

Class1::Class1(){

}


Class1::~Class1(){

}


