///////////////////////////////////////////////////////////
//
//  EnterpriseArchitextClass1.h
//  Implementation of the Class Class1
//  Generated by Enterprise Architect
//  Created on:      25-May-2003 02:48:46
//  Original author: 
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(Class1_26082BDF_3F4C_48dd_BCFE_665AB6B23676__INCLUDED_)
#define Class1_26082BDF_3F4C_48dd_BCFE_665AB6B23676__INCLUDED_

/**
* adfasfdasfsdfdf
*/
class Class1
{

public:
	Class1();
	virtual ~Class1();

private:
	int nIntValue;
};

#endif // !defined(Class1_26082BDF_3F4C_48dd_BCFE_665AB6B23676__INCLUDED_)
