//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HobbyIOMonitor.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HOBBYIOMONITOR_DIALOG       102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDB_BITMAP1_ER1                 129
#define IDR_MENU1                       130
#define IDD_DIALOG_CONFIGURE            131
#define IDB_BITMAP_ANALOGPORTS          133
#define IDB_BITMAP_DIGITALPORTS         134
#define IDD_DIALOG_ANALOG_PORTS         135
#define IDD_DIALOG_DIGITALPORTS         136
#define IDD_DIALOG_CMD_MACRO_PANEL      137
#define IDB_BITMAP1                     140
#define IDC_STATIC_A                    1005
#define IDC_EDIT_A0                     1006
#define IDC_EDIT_A1                     1007
#define IDC_EDIT_A2                     1008
#define IDC_EDIT_A3                     1009
#define IDC_EDIT_A4                     1010
#define IDC_EDIT_A5                     1011
#define IDC_EDIT_A6                     1012
#define IDC_EDIT_A7                     1013
#define IDC_EDIT_A8                     1014
#define IDC_EDIT_A9                     1015
#define IDC_EDIT_A10                    1016
#define IDC_EDIT_A11                    1017
#define IDC_EDIT_A12                    1018
#define IDC_EDIT_A13                    1019
#define IDC_RADIO_ANALOG_DISPLAY_VOLTS  1020
#define IDC_RADIO_ANALOG_DISPLAY_RAW    1021
#define IDC_CHECK_CONTINUOUS_SCAN       1022
#define IDC_BUTTON_SCAN                 1023
#define IDC_EDIT_A15                    1024
#define IDC_RADIO3_FLOATING             1025
#define IDC_RADIO3_STICKEY_LO           1026
#define IDC_RADIO3_LOCAP                1026
#define IDC_RADIO3_STICKEY_HI           1027
#define IDC_RADIO3_HICAP                1027
#define IDC_STATIC_A2                   1028
#define IDC_EDIT_DI0                    1029
#define IDC_EDIT_DI1                    1030
#define IDC_EDIT_DI2                    1031
#define IDC_EDIT_DI3                    1032
#define IDC_EDIT_DI4                    1033
#define IDC_EDIT_DI5                    1034
#define IDC_EDIT_DI6                    1035
#define IDC_RADIODO0HI                  1036
#define IDC_IPADDRESS1                  1037
#define IDC_EDIT_A14                    1037
#define IDC_CHECK_RELOADIPADDRESS       1038
#define IDC_CHECK2                      1039
#define IDC_CHECK_AUTOCONNECT           1039
#define IDC_BUTTON_MACROBUTTON1         1041
#define IDC_CHECK_ENABLE_ANALOGSCANNING 1042
#define IDC_BUTTON_DIGITALPUTMACROBUTTON 1043
#define IDC_BUTTON_DIGITAL_OUTPUT_PRESET0 1043
#define IDC_EDIT_INTERVAL               1044
#define IDC_BUTTON_DIGITALPUTMACROBUTTON2 1045
#define IDC_BUTTON_DIGITAL_OUTPUT_PRESET1 1045
#define IDC_BUTTON1                     1046
#define IDC_BUTTON_DIGITALOUTPUT        1046
#define IDC_RADIO1_DIGITAL_OUTPUTMODE_AUTO 1047
#define IDC_BUTTON_DIGITALPUTMACROBUTTON3 1047
#define IDC_BUTTON_DIGITAL_OUTPUT_PRESET2 1047
#define IDC_EDIT_DI7                    1048
#define IDC_STATIC_A3                   1049
#define IDC_RADIO1_DIGITAL_OUTPUTMODE_MANUAL 1050
#define IDC_BUTTON_DIGITALPUTMACROBUTTON4 1050
#define IDC_BUTTON_DIGITAL_OUTPUT_PRESET3 1050
#define IDC_RADIO2_DISPLAY_BINARY       1051
#define IDC_RADIO2_DISPLAY_TEXT         1052
#define IDC_BUTTON_MACROBUTTON2         1054
#define IDC_BUTTON_CONNECT              1055
#define IDC_IPADDRESS3                  1056
#define IDC_BUTTON_MACROBUTTON3         1057
#define IDC_BUTTON_MACROBUTTON4         1058
#define IDC_RADIODO0LO                  1060
#define IDC_RADIODO1HI                  1061
#define IDC_RADIODO1LO                  1062
#define IDC_RADIODO2HI                  1063
#define IDC_RADIODO2LO                  1064
#define IDC_RADIODO3HI                  1065
#define IDC_RADIODO3LO                  1066
#define IDC_RADIODO4HI                  1067
#define IDC_RADIODO4LO                  1068
#define IDC_RADIODO5HI                  1069
#define IDC_RADIODO5LO                  1070
#define IDC_RADIODO6HI                  1071
#define IDC_RADIODO6LO                  1072
#define IDC_RADIODO7HI                  1073
#define IDC_RADIODO7LO                  1074
#define IDC_CHECK_ENABLE_DIGITAL_SCANNING 1075
#define IDC_EDIT_CMD_AUDIT              1078
#define IDC_EDIT_PORT                   1079
#define IDC_EDIT_DIGITAL_IN             1080
#define IDC_EDIT_PORT2                  1081
#define IDC_EDIT_PASSWORD               1081
#define IDC_EDIT_PORTNUMBER             1082
#define IDC_EDIT_DIGITAL_OUT            1082
#define IDC_CHECK_SHOW_A15_AS_BATTERY   1083
#define IDC_CHECK1                      1087
#define IDC_CHECK_ADD_LINENUMBERS       1087
#define IDC_CHECK3                      1088
#define IDC_EDIT1                       1089
#define IDC_EDIT_COMMANDENTRY           1089
#define IDC_CHECK1_ENABLE_ANALOG        1090
#define IDC_CHECK_ENABLE_DIG_WORD_TRIGGER 1091
#define IDC_RADIO_DISPLAY_BINARY        1092
#define IDC_RADIO_DISPLAY_TEXT          1093
#define IDC_CHECK4                      1097
#define IDC_CHECK_ECHO_DEBUGSTATEMENTS  1097
#define IDC_EDIT2                       1098
#define IDC_EDIT_DO0c                   1098
#define IDC_EDIT_IPADDRESS              1098
#define IDC_EDIT3                       1099
#define IDC_EDIT_DO1c                   1099
#define IDC_EDIT4                       1100
#define IDC_EDIT_DO2c                   1100
#define IDC_EDIT5                       1101
#define IDC_EDIT_DO3c                   1101
#define IDC_CHECK5                      1102
#define IDC_CHECK_SHOWABOUTBOX          1102
#define IDC_EDIT_DO_TOP_CONFIGURE       1103
#define IDC_EDIT_MACRO_ENTRY            1110
#define IDC_TAB_CMD_MACROS              1111
#define IDC_CHECK_ECHO_TO_CMDTRAIL      1116
#define IDC_EDIT_TRIGGER_VAL            1120
#define IDC_CHECK_MSGBOX                1121
#define IDC_BUTTON_COPYDO0              1122
#define IDC_BUTTON_COPYDO1              1123
#define IDC_BUTTON_COPYDO2              1124
#define IDC_BUTTON_COPYDO3              1125
#define IDC_CHECK_REPEAT_TRIGGER        1126
#define IDC_BUTTON_COPY_TRIGGERVAL      1127
#define IDC_EDIT_LICENSE                1128
#define IDC_BUTTON_SENDCOMMAND          1129
#define IDC_BUTTON3                     1130
#define IDC_RADIODO0HIc                 1131
#define IDC_RADIODO0LOc                 1132
#define IDC_RADIODO1HIc                 1133
#define IDC_RADIODO1LOc                 1134
#define IDC_RADIODO2HIc                 1135
#define IDC_RADIODO2LOc                 1136
#define IDC_RADIODO3HIc                 1137
#define IDC_RADIODO3LOc                 1138
#define IDC_RADIODO4HIc                 1139
#define IDC_RADIODO4LOc                 1140
#define IDC_RADIODO5HIc                 1141
#define IDC_RADIODO5LOc                 1142
#define IDC_RADIODO6HIc                 1143
#define IDC_RADIODO6LOc                 1144
#define IDC_RADIODO7HIc                 1145
#define IDC_RADIODO7LOc                 1146
#define IDC_EDIT_NOTIFYMSG              1147
#define ID_ABOUT                        32771
#define IDM_SAVEAS                      32773
#define ID_MENU_ANALOG_DLG              32774
#define ID_MENU_DIGITAL_PORTS_DLG       32775
#define ID_HELP_HELPFILE                32777
#define IDD_MENU_CONFIGURE              65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1151
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
